package sam.api.config;

public interface InjectorKeys {
	String APP_DATA_DIR = "APP_DATA_DIR";
	String DRY_RUN = "DRY_RUN";
	String DEBUG = "DEBUG";
	String TEMP_DIR = "TEMP_DIR";
	String SELF_DIR = "SELF_DIR";
	String MANGA_DIR = "MANGA_DIR";
	String MANGA_DATA_DIR = "MANGA_DATA_DIR";
	String MANGAROCK_INPUT_DIR = "MANGAROCK_INPUT_DIR";
	String MANGAROCK_DB_BACKUP = "MANGAROCK_DB_BACKUP";
	String SAMROCK_DB_OLD = "SAMROCK_DB_OLD";
	String SAMROCK_DB = "SAMROCK_DB";
	String MANGAROCK_DB = "MANGAROCK_DB";
	String SAMROCK_THUMBS_DIR = "SAMROCK_THUMBS_DIR";
	String NEW_MANGAS_TSV_FILE = "NEW_MANGAS_TSV_FILE";
	String UPDATED_MANGAS_TSV_FILE = "UPDATED_MANGAS_TSV_FILE";
	String MISSING_CHAPTERS_FILE = "MISSING_CHAPTERS_FILE";
	String MANGAROCK_INPUT_DB = "MANGAROCK_INPUT_DB";
	String CACHE_DIR = "CACHE_DIR";
}
